openapi: 3.0.3
servers: 
  - url: 'https://api.uanataca.com/api/v1' 
security: []
info:
  title: ESAW ONESHOT API DOCUMENTATION
  description: 
    $ref: ./esaw_oneshot.md
  version: v1


tags:
  - name: Create request
    description: Creates the certificate request
x-tagGroups: 
  - name: API Reference
  - tags:
    - Create request
paths: 
  /esawoneshot:
    $ref: paths/esawoneshot.yaml
  