openapi: 3.0.3
servers: 
  - url: 'https://api.uanataca.com/api/v1' 
security: []
info:
  title: ESAW ONESHOT API DOCUMENTATION
  description: 
    $ref: ./esaw_oneshot.md
  version: v1

x-tagGroups: 
  - name: API Reference
paths: 
  /esawoneshot:
    $ref: paths/esawoneshot.yaml
  