openapi: 3.1.0
security: []
info:
  title: UANATACA ONE-SHOT SIGNATURE API DOCUMENTATION
  description: 
    $ref: ./esaw_oneshot.md
  version: v1
  x-logo:
    url: https://raw.githubusercontent.com/UANATACA/ONESHOT-VIDEOID-REPO/main/img/oneshot_logo.png
    altText: Oneshot logo
servers:
- url: https://one-shot.developers.uanataca.com
tags:
- name: Create
  description: 'desc'

paths:
  /esawoneshot:
    $ref: ./paths/esawoneshot.yaml
x-tagGroups:
- name: API Reference
  tags:
  - Create
