openapi: 3.0.3
servers: 
  - url: 'https://api.uanataca.com/api/v1' 
security: []
info:
  title: ESAW ONESHOT API DOCUMENTATION
  description: 
    $ref: ./esaw_oneshot.md
  version: v1


tags:
  - name: Create
    description: Creates the certificate request
x-tagGroups: 
  - name: API Reference
  - tags:
    - Create
paths: 
  /esawoneshot:
    post:
      tags:
        - Create
      summary: Echo test
      description: Receive the exact message you've sent
      operationId: echo
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
    
          content:
            application/json:
              schema:
                type: string
              examples:
                response:
                  value: Hello world!
            application/xml:
              schema:
                type: string
            text/csv:
              schema:
                type: string
        '400':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: string
              example: Hello world!
          application/xml:
            schema:
              type: string
              example: Hello world!
        description: Echo payload
        required: true
    