openapi: 3.0.1
security: []
info:
  title: UANATACA ONE-SHOT SIGNATURE API DOCUMENTATION
  description: 
    $ref: ./esaw_oneshot.md
  version: v1
  x-logo:
    url: https://raw.githubusercontent.com/UANATACA/ONESHOT-VIDEOID-REPO/main/img/oneshot_logo.png
    altText: Oneshot logo
servers:
- url: https://one-shot.developers.uanataca.com
tags:
- name: Create
  description: 'desc'

paths:
  /api/v1/hello:
    get:
      tags:
      - Create
      summary: HELLO
      description: Checks if server is UP.
      operationId: hello
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
x-tagGroups:
- name: API Reference
  tags:
  - Create
