openapi: 3.0.1
servers: 
  - url: 'https://api.uanataca.com/api/v1' 
security: []
info:
  title: ESAW ONESHOT API DOCUMENTATION
  description: 
    $ref: ./esaw_oneshot.md
  version: v1


tags:
  - name: Create
    description: Creates the certificate request
x-tagGroups: 
  - name: API Reference
  - tags:
    - Create
paths: 
  /api/v1/hello:
    get:
      tags:
      - Create
      summary: HELLO
      description: Checks if server is UP.
      operationId: hello
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties: 
                  status:
                    type: string
                    description: Response status code
                  details:
                    type: string
                    description: Response message
              example:
                status: 200 OK
                details: Hello